#!/usr/bin/env python

import logging
import argparse
import os
import shutil
import rasterio
import xarray as xr
import pandas as pd
import numpy as np
import pystac
from pystac.extensions.projection import ProjectionExtension
from pystac.extensions.render import RenderExtension, Render
from pystac.extensions.raster import RasterExtension, RasterBand, Histogram, Statistics
from shapely.geometry import box, mapping
from shapely.ops import unary_union
from pathlib import Path
from datetime import datetime, timezone

# Configure basic logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("CREATE_STAC")

# Constants
FMT_TIME = "%Y-%m-%d %H:%M:%SZ"

class StacCatalog:
    def __init__(self,id,basepath,title,description):
        self.basepath = basepath
        self.items    = []
        #
        # Create catalog folder
        #
        if os.path.exists(basepath):
            logger.warning("Catalog folder already exists and will be removed")
            shutil.rmtree(basepath)
        os.makedirs(basepath)
        #
        # Create STAC catalog
        #
        self.catalog = pystac.Catalog(
            id          = id,
            title       = title,
            description = description)

    def get_assets(self,files):
        #
        # Get asset list with metadata
        #
        dassets = [self._get_asset(f) for f in files]
        #
        # Group assets by step
        #
        grouped = {}
        for asset in dassets:
            step = asset['step']
            if step in grouped:
                grouped[step].append(asset)
            else:
                grouped[step] = [asset]
        return grouped

    def append_item(self,id,dassets):
         #
        #Add title and description to STAC item properties
        #
        step = dassets[0]["step"]
        ST_title= f"FALL3D model simulation at t0+{step}h"
        ST_description="This item contains different variables generated by the FALL3D simulation"
        #
        # Compute union for Item geometry
        # 
        item_geometry = unary_union([d["geom"] for d in dassets])
        item_bbox     = item_geometry.bounds  # (left, bottom, right, top)
        #
        # Get times
        #
        times = [d['startTime'] for d in dassets]
        

        day = min(times).date()

        start_datetime = datetime.combine(
           day,
           datetime.min.time(),
           tzinfo=timezone.utc
        )

        end_datetime = datetime.combine(
          day + pd.Timedelta(days=1),
          datetime.min.time(),
          tzinfo=timezone.utc
        )
        #
        # Create item
        #
        item = pystac.Item(
            id             = id,
            geometry       = mapping(item_geometry),
            bbox           = item_bbox,
            properties     = {
                "title": ST_title,
                "description": ST_description,
                "author": "lmingari",
                "created": datetime.now(timezone.utc).strftime(FMT_TIME),
            },
            datetime       = None,
            start_datetime = start_datetime,
            end_datetime   = end_datetime,
        )
        #
        # Create subfolder for this item
        #
        dst = os.path.join(self.basepath,id)
        os.makedirs(dst)
        #
        # Add assets
        #
        for dasset in dassets:
            key   = dasset["key"]
            asset = dasset["asset"]
            fname = dasset["fname"]
            logger.debug(f"Processing file: {fname}")
            item.add_asset(key=key,asset=asset)
            #
            # Apply Extensions to the asset
            #
            if 'proj' in dasset:
                proj_ext = ProjectionExtension.ext(item.assets[key], add_if_missing=True)
                proj_ext.apply(**dasset['proj'])
            if 'raster' in dasset:
                raster_ext = RasterExtension.ext(item.assets[key], add_if_missing=True)
                raster_ext.bands = [RasterBand.create(**dasset['raster'])]
            #
            # Copy file asset
            #
            shutil.copy(fname,dst)
        #
        # Apply Extensions to the item
        #
        renders = self._get_renders(dassets)
        if renders:
            render_ext = RenderExtension.ext(item, add_if_missing=True)
            render_ext.renders = {k: Render(v) for k, v in renders.items()}
        #
        # Append to list of items
        #
        self.items.append(item)

    def save(self):
        #
        # Validate item
        #
        for item in self.items: item.validate()
        #
        # Add item to catalog
        #
        self.catalog.add_items(self.items)
        #
        # Save catalog
        #
        self.catalog.normalize_hrefs(self.basepath)
        self.catalog.save(
            catalog_type=pystac.CatalogType.SELF_CONTAINED,
            dest_href=self.basepath
            )

    def _get_asset(self,fname):
        #
        # Initializations
        #
        href = Path(fname).name
        output = dict(
            fname     = fname,
            key       = None,
            asset     = None,
            bbox      = None,
            geom      = None,
            step      = None,
            startTime = None,
            endTime   = None,
            proj      = None,
            raster    = None,
            )
        if fname.endswith(".tif") or fname.endswith(".tiff"):
            #
            # Open raster file
            #
            with rasterio.open(fname) as dst:
                tags = dst.tags()
                ALLOWED_TAGS = {
                    "key",
                    "label",
                    "unit",
                    "time",
                }
                tags = {k: v for k, v in tags.items() if k in ALLOWED_TAGS}
                bbox = dst.bounds
                is_empty = False
                hist_obj, stat_obj = self._get_statistics(dst)
                proj = dict(
                    epsg      = dst.crs.to_epsg(),
                    shape     = (dst.height, dst.width),
                    transform = dst.transform,
                )
                raster = None
                if hist_obj is not None and stat_obj is not None:
                    raster = dict(
                        nodata     = dst.nodata,
                        data_type  = dst.dtypes[0],
                        histogram  = hist_obj,
                        statistics = stat_obj,
                    )
                else:
                    is_empty = True
                

                #raster = dict(
                #    nodata     = dst.nodata,
                #    data_type  = dst.dtypes[0],
                #    histogram  = hist_obj,
                #    statistics = stat_obj,
                #)
            stem = Path(fname).stem  # e.g. tephra_col_mass-t006
            if "-t" in stem:
                step = int(stem.split("-t")[-1])
            else:
                step = 0
            output.update(
                key       = Path(fname).stem,
                bbox      = bbox,
                geom      = box(bbox.left, bbox.bottom, bbox.right, bbox.top),
                step      = step,
                startTime = datetime.strptime(tags["time"],FMT_TIME),
                endTime   = datetime.strptime(tags["time"],FMT_TIME),
                proj      = proj,
                raster    = raster,
                )
            media_type = pystac.MediaType.COG
            #title = f"{tags['key']} for step {tags['step']}"
            label = tags.get("label")
            title = f"{label} at t0+{step}h"
            roles = ["data","visual","render"]
        elif fname.endswith(".nc"):
            #
            # Open netCDF file
            #
            with xr.open_dataset(fname) as ds:
                xmin = ds.lon.minimum
                ymin = ds.lat.minimum
                xmax = ds.lon.maximum + ds.lon.cell_measures
                ymax = ds.lat.maximum + ds.lat.cell_measures
                t1   = pd.Timestamp(ds.time.values[0])
                t2   = pd.Timestamp(ds.time.values[-1])
            output.update(
                key       = Path(fname).stem,
                bbox      = [xmin,ymin,xmax,ymax],
                geom      = box(xmin,ymin,xmax,ymax),
                startTime = t1,
                endTime   = t2,
                )
            tags  = {}
            media_type = pystac.MediaType.NETCDF
            title = "FALL3D res file"
            roles = ["data"]
        else:
            raise ValueError(f"Tried to add a not allowed asset: {fname}")

        output.update(
            asset = pystac.Asset(
                title        = title,
                href         = href,
                media_type   = media_type,
                roles        = roles,
                extra_fields = tags,
            )
        )
        if is_empty:
            output["asset"].extra_fields["empty"] = True

        return {key: value for key, value in output.items() if value is not None}
    
    def _get_statistics(self,src):
        """
        return a histogram and statistics objects 
        required by the raster extension
        """
        # Read data
        #data = src.read(1)
        data = src.read(1).astype(np.float64)
        ndata = int(data.size)

        # Get the NoData value
        nodata_value = src.nodata
        
        # Remove NoData values and flatten the array for processing
        if nodata_value is not None:
            data = data[data != nodata_value]
        else:
            data = data.flatten()

        data = data[~np.isnan(data)]
        nvalid  = int(data.size)
        
        if nvalid == 0:
            return None, None

        logger.info(
            f"{src.name}: size={data.size}, "
            f"nan_count={np.isnan(data).sum()}, "
            f"nodata={nodata_value}"
        )

        min_val = data.min()
        max_val = data.max()

        ncount  = 256
        hist, bin_edges = np.histogram(data,bins=ncount,range=(min_val,max_val))

        stat_obj = Statistics.create(
            minimum       = min_val.item(),
            maximum       = max_val.item(),
            mean          = data.mean().item(),
            stddev        = data.std().item(),
            valid_percent = 100.0*nvalid/ndata,
        )

        hist_obj = Histogram.create(
            count   = ncount,
            min     = min_val.item(),
            max     = max_val.item(),
            buckets = hist.tolist()
        )

        return (hist_obj, stat_obj)

    @staticmethod
    def _get_renders(dassets):
        renders = {}
        for d in dassets:
            asset      = d['asset']
            asset_key  = d['key']
            field_key  = asset.extra_fields.get('key')
            render_key = 'render_'+asset_key

            if field_key in ['SO2_col_mass']:
                conf = dict(
                    title         = "SO2 column mass",
                    assets        = [asset_key],
                    resampling    = "average",
                    colormap_name = "RdYlBu_r",
                    rescale       = [[0.1,2.0]],
                )
            elif field_key in ['tephra_col_mass']:
                conf = dict(
                    title         = "Ash column mass",
                    assets        = [asset_key],
                    resampling    = "average",
                    colormap_name = "RdYlBu_r",
                    rescale       = [[0.1,2.0]],
                )
            elif field_key in ['tephra_cloud_top']:
                conf = dict(
                    title         = "Ash cloud top",
                    assets        = [asset_key],
                    resampling    = "nearest",
                    colormap_name = "viridis",
                    rescale       = [[1000,8000]], 
                )
            elif field_key in ['SO2_cloud_top']:
                conf = dict(
                    title         = "SO2 cloud top",
                    assets        = [asset_key],
                    resampling    = "nearest",
                    colormap_name = "viridis",
                    rescale       = [[1000,8000]], 
                )
            else:
                conf = {}
            if conf: renders[render_key] = conf
        return renders

def main(args):
    #
    # Create STAC catalog
    #
    c = StacCatalog(
        id          = "what-if-demo",
        basepath    = args.path,
        title       = "What-if scenario demonstration",
        description = "STAC catalog for the what-if scenario demo generated by the FALL3D module")
    #
    # Get assets grouped by step
    #
    grouped_assets = c.get_assets(args.cogs)
    for step, assets in grouped_assets.items():
        #
        # Create item
        #
        item_id = f"{step:03d}"
        c.append_item(item_id, assets)
    #
    # Save catalog
    #
    c.save()

if __name__ == "__main__":
    #
    # Argument parser
    #
    parser = argparse.ArgumentParser(description="Create a STAC catalog")
    parser.add_argument("--path",   type=str, required=True, help="STAC Catalog folder path")
    parser.add_argument("--cogs",   type=str, required=True, nargs='+', help="List of COG files")
    args = parser.parse_args()
    #
    # Main program
    #
    logger.info("Creating STAC catalog...")
    main(args)
    logger.info("Done!")
